name: Convert CHEATSHEET.md to PDF

on:
  push:
    paths:
      - CHEATSHEET.md
  pull_request:
    paths:
      - CHEATSHEET.md

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Markdown to AsciiDoc
      run: pandoc CHEATSHEET.md -t asciidoc -o CHEATSHEET.adoc

    - name: Convert AsciiDoc to PDF
      run: docker run --rm --privileged -u $(id -u):$(id -g) -v `pwd`:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf -a stem -r asciidoctor-mathematical CHEATSHEET.adoc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        user_name: 'github-ci[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Publish to gh-pages'
